Almost-functioning way to use a page template JSX (which doesn't contain the <html> container, but leaves that to the controller as a body parameter in the React4xp.render call).
However, since react4xp-regions/Page returns an array of components not wrapped in a single component/container, we have a problem:

com.enonic.lib.react4xp.HtmlInserter -

ERROR: [ org.jdom2.input.JDOMParseException: Error on line 1: The markup in the document following the root element must be well-formed] ...when trying to insert HTML...

<head data-reactroot=""><title>Heppsann</title></head>
<body class="xp-page" data-reactroot=""><div data-portal-region="main" class="xp-region"><!--# COMPONENT /main/0 --></div></body>

...at element with ID '8449440c-8030-4816-aa70-f35baa8a589a' into body:

<html id="8449440c-8030-4816-aa70-f35baa8a589a"></html>